// ENSF380 Lab02
// Farha Ahmed and Hamza Khurram
// Jul 11, 2024
package ca.ucalgary.ensf380;

import java.util.Date;

// This class represents a report generated by an administrator
public class Report {
    private String reportDetails;
    private Date reportDate;

    // Constructor to initialize a report
    public Report(String reportDetails, Date reportDate) {
        this.reportDetails = reportDetails;
        this.reportDate = reportDate;
    }

    // Getters and setters to access and modify report details
    public String getReportDetails() { return reportDetails; }
    public void setReportDetails(String reportDetails) { this.reportDetails = reportDetails; }

    public Date getReportDate() { return reportDate; }
    public void setReportDate(Date reportDate) { this.reportDate = reportDate; }
}
